## TheHive 5 surcharge - cf docker-compose.soar.yml pour les options principales
## Mettre ici uniquement les options non-CLI (ex: SMTP, integrations webhooks)

## Notification - SMTP (optionnel)
notification.webhook.endpoints = []

## SMTP (rapports / notifs cas) - a configurer
play.mailer {
  host = "localhost"
  port = 25
  user = ""
  password = ""
  ssl = false
  tls = false
  mock = true
}
