## Cortex 3 - configuration de base
## A completer avec les API keys des analyzers (Shodan, VT, MISP, etc) via le UI

play.http.secret.key = "${?CORTEX_SECRET_KEY}"

## Database (Elasticsearch)
search {
  index   = cortex
  uri     = "http://elasticsearch:9200"
  keepalive = 10m
  pagesize = 50
  nbshards = 5
  nbreplicas = 1
}

## Authentication
auth {
  provider = [local]
  defaultUserDomain = "digital-printing.local"
  multifactor = []
}

## Cache
cache.job = 10 minutes

## Job runner
job {
  runners = [docker]
  directory = /tmp/cortex-jobs
  dockerDirectory = /tmp/cortex-jobs
}

## Analyzer / Responder repositories (preconfigures)
analyzer {
  urls = [
    "https://download.thehive-project.org/analyzers.json"
  ]
  fork-join-executor {
    parallelism-min = 2
    parallelism-factor = 2.0
    parallelism-max = 4
  }
}

responder {
  urls = [
    "https://download.thehive-project.org/responders.json"
  ]
  fork-join-executor {
    parallelism-min = 2
    parallelism-factor = 2.0
    parallelism-max = 4
  }
}
